# Generated by Django 3.2.4 on 2021-07-03 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yacht01', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(help_text='Мета описание', max_length=255, verbose_name='Description')),
                ('alt', models.CharField(help_text='alt text', max_length=255, verbose_name='Alt')),
                ('order', models.IntegerField(unique=True, verbose_name='order')),
                ('image', models.ImageField(blank=True, upload_to='static/img/portfolio/')),
                ('show', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
