# Generated by Django 3.2.4 on 2021-07-03 15:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yacht01', '0007_portfolio_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['MOV', 'avi', 'mp4', 'webm'])]),
        ),
    ]
